DROP DATABASE IF EXISTS reg_test;
CREATE DATABASE reg_test;

DROP USER IF EXISTS regrstest;
CREATE USER regrstest WITH  PASSWORD '123456';

GRANT ALL PRIVILEGES ON DATABASE reg_test TO rstest;

\c reg_test;
DROP TABLE IF EXISTS RSOI_REGS;
CREATE TABLE RSOI_REGS (
  ID       SERIAL PRIMARY KEY ,
  EVENT_ID INT,
  USER_ID VARCHAR(50)
);

INSERT INTO RSOI_REGS VALUES  (DEFAULT, 1,'simpleUser');
GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA public TO regrstest;
GRANT ALL PRIVILEGES ON ALL SEQUENCES IN SCHEMA public TO regrstest;

