-- noinspection SqlNoDataSourceInspectionForFile

DROP DATABASE IF EXISTS authdb;
CREATE DATABASE authdb;

DROP USER IF EXISTS auth_user;
CREATE USER auth_user WITH  PASSWORD '123456';

GRANT ALL PRIVILEGES ON DATABASE authdb TO auth_user;

\c authdb;

CREATE EXTENSION pgcrypto;

DROP TABLE IF EXISTS AUTH_INFO;
CREATE TABLE AUTH_INFO (
  ID       SERIAL PRIMARY KEY ,
  LOGIN    VARCHAR(256),
  PASSHASH VARCHAR(1024)
);

DROP TABLE IF EXISTS CLIENTS_INFO;
CREATE TABLE CLIENTS_INFO(
  ID             SERIAL PRIMARY KEY,
  SECRET         VARCHAR(256),
  REDIR_URL      VARCHAR(256)
);
-- 123456 123123, salt 123456
INSERT INTO EVENTS_INFO VALUES  (DEFAULT, 'eventOwner', '12tir.zIbWQ3c');
INSERT INTO EVENTS_INFO VALUES  (DEFAULT, 'simpleUser', '12vjy8B6VZQUU');
INSERT INTO CLIENTS_INFO VALUES  (DEFAULT, '12tir.zIbWQ3c', 'loclhost:9191/token');
GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA public TO events_user;
