DROP DATABASE IF EXISTS regsdb;
CREATE DATABASE regsdb;

DROP USER IF EXISTS regs_user;
CREATE USER regs_user WITH  PASSWORD '123456';

GRANT ALL PRIVILEGES ON DATABASE regsdb TO regs_user;

\c regsdb;
DROP TABLE IF EXISTS RSOI_REGS;
CREATE TABLE RSOI_REGS (
  ID       SERIAL PRIMARY KEY ,
  EVENT_ID BIGINT,
  USER_ID  BIGINT
);

GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA public TO regs_user;
GRANT ALL PRIVILEGES ON ALL SEQUENCES IN SCHEMA public TO regs_user;
