DROP DATABASE IF EXISTS events_test;
CREATE DATABASE events_test;

DROP USER IF EXISTS eventtest;
CREATE USER eventtest WITH  PASSWORD '123456';

GRANT ALL PRIVILEGES ON DATABASE events_test TO eventtest;

\c events_test;

DROP TABLE IF EXISTS EVENTS_INFO;
CREATE TABLE EVENTS_INFO (
  ID       SERIAL PRIMARY KEY ,
  OWNERID VARCHAR(256),
  PARTICIPANT_COUNT INT DEFAULT(0),
  DESCRIPTION VARCHAR(1024)
);

INSERT INTO EVENTS_INFO VALUES  (DEFAULT, 'eventOwner', DEFAULT , 'KISH concert');
INSERT INTO EVENTS_INFO VALUES  (DEFAULT, 'eventOwner', DEFAULT , 'OP concert');
GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA public TO eventtest;
