DROP DATABASE IF EXISTS users_test;
CREATE DATABASE users_test;

DROP USER IF EXISTS rstest;
CREATE USER rstest WITH  PASSWORD '123456';

GRANT ALL PRIVILEGES ON DATABASE users_test TO rstest;

\c users_test;

DROP TABLE IF EXISTS USER_INFO;
CREATE TABLE USER_INFO (
  ID       SERIAL PRIMARY KEY ,
  USERNAME VARCHAR(256),
  EVENTS_NUMBER INT DEFAULT(0)
  );
INSERT INTO USER_INFO VALUES  (DEFAULT, 'simpleUser', DEFAULT);
GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA public TO rstest;
